Run("D:\Maxence\Documents\GitHub\Autoit\vnc-viewer-installer\VNC-Viewer-6.21.406-Windows")
WinWaitActive("CLASS:os::Window::Dialog", "",1)
ControlClick("Programme d'installation VNC Viewer","","[CLASS:Button; INSTANCE:1]")
Sleep(2000)
ControlClick("Installation de VNC Viewer 6.21.406","","[CLASS:Button; INSTANCE:2]")
Sleep(1000)
Send("{SPACE}")
ControlClick("Installation de VNC Viewer 6.21.406","","[CLASS:Button; INSTANCE:4]")
Sleep(1000)
Send("{DOWN}")
Sleep(100)
Send("{SPACE}")
Sleep(100)
Send("{DOWN}")
Sleep(100)
Send("{ENTER}")
ControlClick("Installation de VNC Viewer 6.21.406","","[CLASS:Button; INSTANCE:5]")
Sleep(1000)
ControlClick("Installation de VNC Viewer 6.21.406","","[CLASS:Button; INSTANCE:1]")
Sleep(5000)
ControlClick("Installation de VNC Viewer 6.21.406","","[CLASS:Button; INSTANCE:1]")